/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as RequestRouteImport } from './routes/request'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ApiAnthropicRouteImport } from './routes/api/anthropic'
import { Route as ApiAskRouteImport } from './routes/api/ask'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiWatchRunRouteImport } from './routes/api/watch-run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnthropicRoute = ApiAnthropicRouteImport.update({
  id: '/api/anthropic',
  path: '/api/anthropic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchRunRoute = ApiWatchRunRouteImport.update({
  id: '/api/watch-run',
  path: '/api/watch-run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/intel': typeof IntelRoute
  '/request': typeof RequestRoute
  '/workspace': typeof WorkspaceRoute
  '/api/anthropic': typeof ApiAnthropicRoute
  '/api/ask': typeof ApiAskRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/watch-run': typeof ApiWatchRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/intel': typeof IntelRoute
  '/request': typeof RequestRoute
  '/workspace': typeof WorkspaceRoute
  '/api/anthropic': typeof ApiAnthropicRoute
  '/api/ask': typeof ApiAskRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/watch-run': typeof ApiWatchRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/intel': typeof IntelRoute
  '/request': typeof RequestRoute
  '/workspace': typeof WorkspaceRoute
  '/api/anthropic': typeof ApiAnthropicRoute
  '/api/ask': typeof ApiAskRoute
  '/api/feed': typeof ApiFeedRoute
  '/api/watch-run': typeof ApiWatchRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/intel'
    | '/request'
    | '/workspace'
    | '/api/anthropic'
    | '/api/ask'
    | '/api/feed'
    | '/api/watch-run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/intel'
    | '/request'
    | '/workspace'
    | '/api/anthropic'
    | '/api/ask'
    | '/api/feed'
    | '/api/watch-run'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/intel'
    | '/request'
    | '/workspace'
    | '/api/anthropic'
    | '/api/ask'
    | '/api/feed'
    | '/api/watch-run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  IntelRoute: typeof IntelRoute
  RequestRoute: typeof RequestRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiAnthropicRoute: typeof ApiAnthropicRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiFeedRoute: typeof ApiFeedRoute
  ApiWatchRunRoute: typeof ApiWatchRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anthropic': {
      id: '/api/anthropic'
      path: '/api/anthropic'
      fullPath: '/api/anthropic'
      preLoaderRoute: typeof ApiAnthropicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watch-run': {
      id: '/api/watch-run'
      path: '/api/watch-run'
      fullPath: '/api/watch-run'
      preLoaderRoute: typeof ApiWatchRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  IntelRoute: IntelRoute,
  RequestRoute: RequestRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiAnthropicRoute: ApiAnthropicRoute,
  ApiAskRoute: ApiAskRoute,
  ApiFeedRoute: ApiFeedRoute,
  ApiWatchRunRoute: ApiWatchRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
